import { createSlice } from "@reduxjs/toolkit";

const initialState = [
    {   name: "John Doe",
        id: 1,
        primarySkill: "React",
        moreSkills: "SCSS, Webpack, Typescript, Next.js",
        dateOfBirth: "26.06.1985",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        hobby: ["acting", "swimming", "gym"],
        educationHistory: "Lorem ipsum dolor sit amet",
        listOfRecentProjects: "this is the projects of this guy"
    },
    {   name: "Dean Cooper",
        id: 2,
        primarySkill: "Java",
        moreSkills: "SQL, REST, Spring, Hibernate",
        dateOfBirth: "21.09.1980",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        hobby: ["video games", "kickboxing", "gym"],
        educationHistory: "Lorem ipsum dolor sit amet",
        listOfRecentProjects: "this is the projects of this guy"
    },
    {   name: "Brenda Margolis",
        id: 3,
        primarySkill: "NodeJS",
        moreSkills: "GIT, C#, SCSS, REST",
        dateOfBirth: "03.05.1978",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        hobby: ["pilates", "painting", "boxing", "hiking"],
        educationHistory: "Lorem ipsum dolor sit amet",
        listOfRecentProjects: "this is the projects of this guy"
    },
    {   name: "Fernando Baker",
        id: 4,
        primarySkill: "React",
        moreSkills: "NodeJS, Webpack, SCSS",
        dateOfBirth: "10.04.1990",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        hobby: ["fishing", "mathematic", "poems"],
        educationHistory: "Lorem ipsum dolor sit amet",
        listOfRecentProjects: "this is the projects of this guy"
    },
    {   name: "Bernice Moore",
        id: 5,
        primarySkill: "Angular",
        moreSkills: "Typescript, jQuery, Java",
        dateOfBirth: "13.10.1996",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        hobby: ["acting", "video games", "swimming", "drawing"],
        educationHistory: "Lorem ipsum dolor sit amet",
        listOfRecentProjects: "this is the projects of this guy"
    },
    {   name: "Matthew Mealy",
        id: 6,
        primarySkill: "NodeJS",
        moreSkills: "GIT, SQL, Java",
        dateOfBirth: "27.06.1970",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        hobby: ["acting", "swimming", "gym"],
        educationHistory: "Lorem ipsum dolor sit amet",
        listOfRecentProjects: "this is the projects of this guy"
    },
    {   name: "Katherine McLee",
        id: 7,
        primarySkill: "Java",
        moreSkills: "Spring, Hibernate, Javascript",
        dateOfBirth: "26.06.1985",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        hobby: ["pilates", "dance", "music"],
        educationHistory: "Lorem ipsum dolor sit amet",
        listOfRecentProjects: "this is the projects of this guy"
    },
    {   name: "Tanya Sam",
        id: 8,
        primarySkill: "React",
        moreSkills: "Next.js, jQuery, GIT, SQL",
        dateOfBirth: "26.10.1990",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        hobby: ["acting", "singing", "painting"],
        educationHistory: "Lorem ipsum dolor sit amet",
        listOfRecentProjects: "this is the projects of this guy"
    },
    {   name: "Carmen Mason",
        id: 9,
        primarySkill: "Angular",
        moreSkills: "SQL, React, Java",
        dateOfBirth: "07.07.1999",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        hobby: ["swimming", "video games", "gym"],
        educationHistory: "Lorem ipsum dolor sit amet",
        listOfRecentProjects: "this is the projects of this guy"
    },
    {   name: "Frank Segura",
        id: 10,
        primarySkill: "NodeJS",
        moreSkills: "C#, .NET Core, Java",
        dateOfBirth: "02.02.1981",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        hobby: ["singing", "swimming", "fishing"],
        educationHistory: "Lorem ipsum dolor sit amet",
        listOfRecentProjects: "this is the projects of this guy"
    },
    {   name: "James Christensen",
        id: 11,
        primarySkill: "React",
        moreSkills: "NodeJS, jQuery, SQL",
        dateOfBirth: "07.11.1993",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        hobby: ["video games", "swimming"],
        educationHistory: "Lorem ipsum dolor sit amet",
        listOfRecentProjects: "this is the projects of this guy"
    },
    {   name: "Moira Clegg",
        id: 12,
        primarySkill: "Java",
        moreSkills: "C#, SQL, React",
        dateOfBirth: "31.05.1986",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        hobby: ["pilates", "kickboxing", "dancing"],
        educationHistory: "Lorem ipsum dolor sit amet",
        listOfRecentProjects: "this is the projects of this guy"
    },
    {   name: "Tomas Wilson",
        id: 13,
        primarySkill: "Java",
        moreSkills: "Hibernate, Springy, SQL",
        dateOfBirth: "04.01.1987",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        hobby: ["dancing", "cycling"],
        educationHistory: "Lorem ipsum dolor sit amet",
        listOfRecentProjects: "this is the projects of this guy"
    },
    {   name: "Marilyn Cohen",
        id: 14,
        primarySkill: "NodeJS",
        moreSkills: "Typescript, Angular, Java",
        dateOfBirth: "26.06.1979",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        hobby: ["acting", "swimming", "pilates"],
        educationHistory: "Lorem ipsum dolor sit amet",
        listOfRecentProjects: "this is the projects of this guy"
    },
    {   name: "Mary Hernandez",
        id: 15,
        primarySkill: "Angular",
        moreSkills: "Typescript, SCSS, React, NodeJS",
        dateOfBirth: "18.08.1990",
        bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        hobby: ["pilates", "swimming", "oil painting", "calligraphy"],
        educationHistory: "Lorem ipsum dolor sit amet",
        listOfRecentProjects: "this is the projects of this guy"
    },
]

const candidatesDataSlice = createSlice({
    name: "candidatesData",
    initialState,
    reducers: {
        addCandidate: (state, action) => {
            const newCandidate = {
                name: action.payload.name,
                id: Date.now(),
                primarySkill: action.payload.primarySkill,
                moreSkills: action.payload.moreSkills,
                dateOfBirth: action.payload.dateOfBirth,
                bio: action.payload.bio,
                hobby: action.payload.hobby,
                educationHistory: action.payload.educationHistory,
                listOfRecentProjects: action.payload.listOfRecentProjects
            };
            state.unshift(newCandidate);
        }
    }
});

export const { addCandidate } = candidatesDataSlice.actions;

export default candidatesDataSlice.reducer;